#!/usr/bin/env zsh
# Open VS Code at repository root

if [[ $# -ge 1 ]]; then
  command code $*
else
  if git rev-parse --is-inside-work-tree &> /dev/null; then
    command code $(command git rev-parse --show-toplevel)
  else
    command code
  fi
fi
