#!/usr/bin/env zsh
# Open VS Code at repository root

if [[ $# -ge 1 ]]; then
  code $*
else
  if git rev-parse --is-inside-work-tree &> /dev/null; then
    code $(git rev-parse --show-toplevel)
  else
    code
  fi
fi
