#!/usr/bin/env zsh
# Insert the selected git unstaged files into the command line

if ! git rev-parse --is-inside-work-tree &> /dev/null; then
  return
fi

local files=$(git ls-files -mo --exclude-standard "$(git rev-parse --show-toplevel)" | uniq | fzf-tmux -m)
[[ -z $files ]] && return

files=${files//\ /\\\ }
files=${files//$'\n'/\ }

LBUFFER=${LBUFFER}${files}
zle reset-prompt
typeset -f zle-line-init > /dev/null && zle zle-line-init
