language: ruby
rvm:
  - 2.4
os:
  - osx
branches:
  only:
    - master
before_install:
  - bundle install
  - brew update
  - brew --version
  - mkdir -pv
    $HOME/.aws
    $HOME/.ssh
    $HOME/Dropbox/.share/.aws
    $HOME/Dropbox/.share/.ssh
    $HOME/Library/Application\ Support/Code/User
  - touch
    $HOME/Dropbox/.share/.aws/config
    $HOME/Dropbox/.share/.aws/credentials
    $HOME/Dropbox/.share/.gitconfig.local
    $HOME/Dropbox/.share/.ssh/config
    $HOME/Dropbox/.share/.zshenv.local
install:
  - brew install zsh
  - make shell
  - yes | make symlink
script:
  - make test
  - "/usr/local/bin/zsh -cli 'true'"
notifications:
  slack:
    secure: BcQGo3/RVeWecGJMCAnqiuFsnUJdzFWCNH7vYJxWAwEmCGa+EW17gY9m9eZf6BK9hcWcCnYGGlhCEU05nJDEW6W5khka7MQT6nHId6EgtYvibQrAfeDdRcbLXyE1q9/dvHG9jQbdnjealeZ6QhE8RnBKkP9fsgKpEnFt/Mu92cfcBQc68asEvmAdBs5Yu6QK4NwBLEN9klUQrnGpMP6mZ2gwdcGlwjOXy0ntqccxJhvzbD11l/dsR8qJ1ebH5dcwGrVdiz5GoNkwHuJVK9CogPg86zKFywuK+N9UnsBHGkbSbHepPcO4qFPTpBDzMsXEKD/EOv56LkZPFXjVx/fS2DIFcc/h6OYiLqWfQZJQBlw0BsLJzl69+dlSJSwOAZpkZ2XLwFELanQ2nB5rDlQwgCrH0SgLWcD4EapFtvj1vzCUkJEw3++PCqmWSid+40oDGUwmu0cbJOgNpgBRI0udxAzVCfx44AVe6NlcbK6C++9App7VpA8r2lXxVwmV96Mqku5rk8pI2rbfTDSsAFdiJUgk+XuMunLOT6uEyDCKFS9FVc6DDd7ONbwwuoDhS8A6Q2XT9qAxaJu6MW1cUBcasvJ7TPw4JlS6CcnbIn1kna94iFixXN/iDUygxWYmaSyQV3zS5RQ9JGFNvbbGjMJy5TeFtVz8uNkhkDRsoePh97Q=
