require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

LineLength:
  Max: 127

ClassAndModuleChildren:
  Enabled: false
