require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 127

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
