require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - bin/*

Documentation:
  Enabled: false

LineLength:
  Max: 127

ClassAndModuleChildren:
  Enabled: false
