require: rubocop-rspec

AllCops:
  Includes:
    - Rakefile
    - Gemfile
    - config.ru
  Excludes:
    - bin/*

Documentation:
  Enabled: false

LineLength:
  Max: 127

ClassAndModuleChildren:
  Enabled: false
