require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 127

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
